//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\UCUM.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUCUMListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
//[System.CLSCompliant(false)]
public partial class UCUMBaseListener : IUCUMListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.mainTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainTerm([NotNull] UCUMParser.MainTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.mainTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainTerm([NotNull] UCUMParser.MainTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] UCUMParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] UCUMParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponent([NotNull] UCUMParser.ComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponent([NotNull] UCUMParser.ComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.annotatable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotatable([NotNull] UCUMParser.AnnotatableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.annotatable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotatable([NotNull] UCUMParser.AnnotatableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.simpleUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleUnit([NotNull] UCUMParser.SimpleUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.simpleUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleUnit([NotNull] UCUMParser.SimpleUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.simpleUnitSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleUnitSymbols([NotNull] UCUMParser.SimpleUnitSymbolsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.simpleUnitSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleUnitSymbols([NotNull] UCUMParser.SimpleUnitSymbolsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.annotationSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationSymbols([NotNull] UCUMParser.AnnotationSymbolsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.annotationSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationSymbols([NotNull] UCUMParser.AnnotationSymbolsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.squareBracketsSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSquareBracketsSymbols([NotNull] UCUMParser.SquareBracketsSymbolsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.squareBracketsSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSquareBracketsSymbols([NotNull] UCUMParser.SquareBracketsSymbolsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinSbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithinSbSymbol([NotNull] UCUMParser.WithinSbSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinSbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithinSbSymbol([NotNull] UCUMParser.WithinSbSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinCbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithinCbSymbol([NotNull] UCUMParser.WithinCbSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinCbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithinCbSymbol([NotNull] UCUMParser.WithinCbSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinCbOrSbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithinCbOrSbSymbol([NotNull] UCUMParser.WithinCbOrSbSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinCbOrSbSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithinCbOrSbSymbol([NotNull] UCUMParser.WithinCbOrSbSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.terminalUnitSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalUnitSymbol([NotNull] UCUMParser.TerminalUnitSymbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.terminalUnitSymbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalUnitSymbol([NotNull] UCUMParser.TerminalUnitSymbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] UCUMParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] UCUMParser.ExponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.digitSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDigitSymbols([NotNull] UCUMParser.DigitSymbolsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.digitSymbols"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDigitSymbols([NotNull] UCUMParser.DigitSymbolsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
