//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\UCUM.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UCUMParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
//[System.CLSCompliant(false)]
public interface IUCUMListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.mainTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainTerm([NotNull] UCUMParser.MainTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.mainTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainTerm([NotNull] UCUMParser.MainTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] UCUMParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] UCUMParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponent([NotNull] UCUMParser.ComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponent([NotNull] UCUMParser.ComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.annotatable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotatable([NotNull] UCUMParser.AnnotatableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.annotatable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotatable([NotNull] UCUMParser.AnnotatableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.simpleUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleUnit([NotNull] UCUMParser.SimpleUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.simpleUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleUnit([NotNull] UCUMParser.SimpleUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.simpleUnitSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleUnitSymbols([NotNull] UCUMParser.SimpleUnitSymbolsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.simpleUnitSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleUnitSymbols([NotNull] UCUMParser.SimpleUnitSymbolsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.annotationSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationSymbols([NotNull] UCUMParser.AnnotationSymbolsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.annotationSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationSymbols([NotNull] UCUMParser.AnnotationSymbolsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.squareBracketsSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSquareBracketsSymbols([NotNull] UCUMParser.SquareBracketsSymbolsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.squareBracketsSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSquareBracketsSymbols([NotNull] UCUMParser.SquareBracketsSymbolsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinSbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithinSbSymbol([NotNull] UCUMParser.WithinSbSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinSbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithinSbSymbol([NotNull] UCUMParser.WithinSbSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinCbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithinCbSymbol([NotNull] UCUMParser.WithinCbSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinCbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithinCbSymbol([NotNull] UCUMParser.WithinCbSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.withinCbOrSbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithinCbOrSbSymbol([NotNull] UCUMParser.WithinCbOrSbSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.withinCbOrSbSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithinCbOrSbSymbol([NotNull] UCUMParser.WithinCbOrSbSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.terminalUnitSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalUnitSymbol([NotNull] UCUMParser.TerminalUnitSymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.terminalUnitSymbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalUnitSymbol([NotNull] UCUMParser.TerminalUnitSymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExponent([NotNull] UCUMParser.ExponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExponent([NotNull] UCUMParser.ExponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCUMParser.digitSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDigitSymbols([NotNull] UCUMParser.DigitSymbolsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCUMParser.digitSymbols"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDigitSymbols([NotNull] UCUMParser.DigitSymbolsContext context);
}
